name: hobby-orchestrators

include:
  - compose/proxy.yml
  - compose/websites.yml
  - compose/services.yml
  - compose/docs.yml
  - compose/observability.yml

networks:
  hobby-internal:
    name: hobby-internal
    internal: true
  hobby-public:
    name: hobby-public
    driver: bridge
    internal: false
