services:
  docs:
    build:
      context: ../../../git-repositories/docs
      target: base
    working_dir: /app
    volumes:
      - ../../../git-repositories/docs:/app
      - docs-node-modules:/app/node_modules
    entrypoint: ["sh", "-c", "npm install && npx likec4 start --hostname 0.0.0.0 --port 80"]

volumes:
  docs-node-modules:
