services:
  placeholder1-service:
    image: golang:1.26-alpine
    working_dir: /app
    volumes:
      - ../../../git-repositories/services/placeholder1-service:/app
    entrypoint: ["go", "run", "."]

  placeholder2-service:
    image: golang:1.26-alpine
    working_dir: /app
    volumes:
      - ../../../git-repositories/services/placeholder2-service:/app
    entrypoint: ["go", "run", "."]
