services:
  web-frontend:
    build:
      context: ../../../git-repositories/services/web-frontend
      target: builder
    working_dir: /app
    volumes:
      - ../../../git-repositories/services/web-frontend:/app
    entrypoint: ["go", "run", "."]
    environment:
      - PORT=8080
      - STATIC_DIR=/app/static
      - ENVIRONMENT=local
